Chef install morden and varia themes for supporting.o.o
openstreetmap/chef pull request #661
Opened 2024-04-23 21:13 UTC by grischard

2024-04-23 21:30 UTC, tomhughes requested changes

2024-04-23 21:30 UTC, tomhughes commented on cookbooks/civicrm/recipes/default.rb
> +  theme "morden"
You don't need to repeat the theme name if it's the same as the resource name - it's the name property so is defaulted automatically.

2024-04-24 09:48 UTC, Firefishy commented
I am wondering if switching the code to [wp-cli theme install](https://developer.wordpress.org/cli/commands/theme/install/)  might be a better option.

2024-04-24 17:48 UTC, tomhughes commented
> I am wondering if switching the code to [wp-cli theme install](https://developer.wordpress.org/cli/commands/theme/install/) might be a better option.

We already discussed that - does that actually do the install itself or does it just call the API on the site and ask it to do the install, which will then have the same permissions issues as using the web interface?

2024-04-24 17:49 UTC, grischard commented
@Firefishy this also works, and the wp-cli path runs into handling output, permissions, etc. Unless we can think of concrete advantages to doing this with wp-cli, let's not let perfect be the enemy of good?

2024-05-11 18:37 UTC, merged